1. Getting started with NumPy

In [20]:
#NumPy by GFG 
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

print('-------------------------------------------------')

lst = [[1,2,3],
    [4,5,6],
    [7,8,9]]
print(lst)
print(type(lst))
print('-------------------------------------------------')

arr = np.array(lst)         #converting the list into array
print(arr)

print('-------------------------------------------------')

print(arr)

print('-------------------------------------------------')

print(type(arr))

print('-------------------------------------------------')

print(arr.ndim)   #shows dimension of the array

print('-------------------------------------------------')

print(arr.shape)     #this gives the shape of the array (rows, columns) : (3, 3)

print('-------------------------------------------------')

print(arr.size)      #gives the size(no. of elements) in the array

print('-------------------------------------------------')

print(arr.dtype)         #This is integer of 32 base; it tells what type of data is stored in the numpy array.

print('-------------------------------------------------')

zeroes = np.zeros((3,3))                 #this prints an n-dimensional array of shape(n,m) with all the elements as 0
print(zeroes)

print('-------------------------------------------------')

ones = np.ones((3,3))                      #this prints an n-dimensional array of shape (n,m) with all the elements as 1
ones


[1 2 3 4 5]
-------------------------------------------------
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
-------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------------------------------------------
<class 'numpy.ndarray'>
-------------------------------------------------
2
-------------------------------------------------
(3, 3)
-------------------------------------------------
9
-------------------------------------------------
int32
-------------------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------------------------------------------


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

2. Reshaping the array and Random number generator

In [21]:
import numpy as np
#generating the random number, which is very useful in game developing algorithms
np.random.random((3,3))                  #this generates the array of shape (3,3) with element ranging from 0-1

array([[0.17101226, 0.7164853 , 0.87921061],
       [0.78743858, 0.23054001, 0.69339879],
       [0.94265592, 0.17878615, 0.82173528]])

In [22]:
#generate the random number between 0-1
np.random.random() 

0.46352394320164647

In [23]:
if np.random.random() > 0.5:
    print("run the function")
else:
    print("Don't run the function")
    

run the function


In [24]:
#To generate the random in sequence(or in some order)
np.arange(1,11,3)                       #This arange() function is like for loop which will have starting index, stop index, step index
#np.random(start,end,step)

array([ 1,  4,  7, 10])

In [25]:
np.linspace(1,10,11)                #this is also same like np.arange which starts from : goes till the end with equidistance
#np.linspace(START, END, how many elements do you want between 1-10)


array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [ ]:
import pandas as pd
a = pd.DataFrame([pd.arange[0,90,3]])

In [26]:
#Reshaping an array
a = np.random.random((4,3))
print(a)

[[0.17293396 0.91282762 0.8518282 ]
 [0.39909512 0.54152641 0.65110147]
 [0.94934015 0.69161803 0.29142142]
 [0.37619096 0.89464297 0.42356833]]


In [27]:
a.shape 

(4, 3)

In [28]:
a.size

12

In [29]:
a.dtype

dtype('float64')

In [30]:
a = np.reshape(a, (3,4))                     #reshaping the shape of the array using reshape() function
a
#here we have to just call the old array, shape of the array(which shape we wanted) 

array([[0.17293396, 0.91282762, 0.8518282 , 0.39909512],
       [0.54152641, 0.65110147, 0.94934015, 0.69161803],
       [0.29142142, 0.37619096, 0.89464297, 0.42356833]])

When we can reshape an array?  Can be done only when the array is of the same size.

In [31]:
#flatten() function which converts the 2D into 1D array
a.flatten()
#name_of_the_function.flatten()

array([0.17293396, 0.91282762, 0.8518282 , 0.39909512, 0.54152641,
       0.65110147, 0.94934015, 0.69161803, 0.29142142, 0.37619096,
       0.89464297, 0.42356833])

3. Arithmetic Operations on Array

In [32]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr) 

#Add 1 to all the elements of the array  [expected o/t : [2,3,4,5,6,7]]
print(arr + 1)
print(arr - 1)
print(arr * 2)
print(arr / 2)
print(arr // 2)
print(arr ** 2)
print(arr.max())    #returns the maximum element in the array, arr
print(arr.min())    #similarly returns the minimum element

#create a 2D array
a = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(a)
#find out the max and min element in the 2D array
print(a.max(axis = 0))   #this gives the maximum element in the column for example 7 in 1st, 8 in 2nd, 9 in 3rd column
print(a.max(axis = 1))   #axis = 0 for column and axis = 1 for row
print(a.min(axis = 0))   #this gives the minimum element in the column for example 1 in 1st, 4 in 2nd, 7 inn 3rd column
print(a.min(axis = 1))
print(a.sum())           #this gives the sum of all the elements of the array

[1 2 3 4 5]
[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]
[ 1  4  9 16 25]
5
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
[3 6 9]
[1 2 3]
[1 4 7]
45


4. Arithmetic Operations on Multiple Arrays


In [ ]:
import numpy as np
a1 = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

a2 = np.array([[9,8,7],
            [6,5,4],
            [3,2,1]])

a3 = np.array([[9,8,7,5],
            [6,5,4,2],
            [3,2,1,5]])


#adding 2D arrays
print(a1 + a2)
print('--------------')
#print(a1 + a3)   #This can't be added bcz both the arrayss are of different shape
print(a1 - a2)
print('--------------')
print(a1 * a2)
print('--------------')
#Dot product(multiplication)
a = a1.dot(a2)     #multiplies each row element with corresponding column element
print(a)
print('--------------')
b = a2.dot(a1)
print(b)
print('--------------')

#Indexing of an 2D array
print(a1[0, 0])              #a1[row_index, column_index]
print('--------------')
print(a1[0, :])              #Row access - access the entire 0th row
print(a1[: , 0])             #Column access - access the entire 0th column
print('--------------')

#Slicing - this allows us to extract subarryas using the format [start:end:step]

print(a2[0:2, :])            #slice the first 2 rows of the array a2 
print(a2[: , 1:3])           #slice the last 2 columns of the array a2
print('--------------') 
print(a1[1:2, 1:2])          #slice the  1st row and 1st column
print('--------------')
print(a1[1: , 1:])           #slice the 1st till last row and 1st till last column elements
print('--------------')

#Fancy indexing - access the specific rows & columns using lists or arrays of indices

print(a2[[0,2], 0])         #slicing the first & third rows.
print(a2[: , [0,2]])        #slice the first & third columns
print('--------------')

#Boolean indexing - allows you to filter elements based on conditions

print(a3[a3>2])             #access the elements that are greater than 2



[[10 10 10]
 [10 10 10]
 [10 10 10]]
--------------
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
--------------
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
--------------
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
--------------
[[ 90 114 138]
 [ 54  69  84]
 [ 18  24  30]]
--------------
#1
1
--------------
#2
[1 2 3]
[1 4 7]
--------------
#3
[[9 8 7]
 [6 5 4]]
[[8 7]
 [5 4]
 [2 1]]
--------------
#4
[[5]]
--------------
#5
[[5 6]
 [8 9]]
--------------
#6
[9 3]
[[9 7]
 [6 4]
 [3 1]]
--------------
#7
[9 8 7 5 6 5 4 3 5]


4. Array Sorting

In [34]:
import numpy as np
a = np.array([[7,3,2,1,5], [5,4,2,6,7],[1,5,7,9,2]])
print(a)
print('--------------')

#sorting using np.sort()
print(np.sort(a, axis = 1, kind = 'mergesort'))           #row wise sorting
print('--------------')
print(np.sort(a, axis = 0, kind = 'quicksort'))           #column wise sorting
print('--------------')
print(np.sort(a, kind = 'mergesort'))                     #default row wise sort




[[7 3 2 1 5]
 [5 4 2 6 7]
 [1 5 7 9 2]]
--------------
[[1 2 3 5 7]
 [2 4 5 6 7]
 [1 2 5 7 9]]
--------------
[[1 3 2 1 2]
 [5 4 2 6 5]
 [7 5 7 9 7]]
--------------
[[1 2 3 5 7]
 [2 4 5 6 7]
 [1 2 5 7 9]]


5. Array Merging

In [35]:
#Lets learn how to concatinate the array
import numpy as np
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a2 = np.array([[8,7,6,5],[4,3,2,1]])
print(a1)
print('------------')
print(a2)
print('------------')
#VERTTICAL STACK
print(np.vstack((a1,a2)))             #np.vstack is used for merging 2 arrays into 1
print('------------')
print(np.vstack((a2, a1)))             #reversing the arrays and merging
print('------------')
#HORIZONTAL STACK
print(np.hstack((a1, a2)))             #horizontal stacking the 2 arrays
print('------------')
print(np.hstack((a2, a1)))
print('------------')
print(np.concatenate((a1, a2), axis = 0))     #default axis = 0 (column wise)
print('------------')
print(np.concatenate((a1, a2), axis = 1))
print('------------')

#Splitting
# horizontally
print(np.hsplit(a1, 2))
print('------------')
# vertically
print(np.vsplit(a1, 2))

[[1 2 3 4]
 [5 6 7 8]]
------------
[[8 7 6 5]
 [4 3 2 1]]
------------
[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]
------------
[[8 7 6 5]
 [4 3 2 1]
 [1 2 3 4]
 [5 6 7 8]]
------------
[[1 2 3 4 8 7 6 5]
 [5 6 7 8 4 3 2 1]]
------------
[[8 7 6 5 1 2 3 4]
 [4 3 2 1 5 6 7 8]]
------------
[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]
------------
[[1 2 3 4 8 7 6 5]
 [5 6 7 8 4 3 2 1]]
------------
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
------------
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


Video 6 Array Slicing

In [36]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0])
print('------------')
print(a[ : 2])
print('------------')
a1 = np.array([[1,2,3,4],
            [5,6,7,8],
            [8,7,6,5],
            [4,3,2,1]])
print(a1)
print('------------')
#a( : , : ) --> a(row_condition , col_condition)
print(a1[ : , : ])       #printing all elements
print('------------')
print(a1[1: , : ])       #1st,2nd, 3rd rows & all columns
print('------------')
print(a1[2, : ])         #only 1st row & all columns
print('------------')
print(a1[1 : , 1 : ])    #selecting 1st, 2nd, 3rd - rows & columns
print('------------')
print(a1[1 : , 1 : 2])   #selected only 1st column and 1st, 2nd, 3rd rows
print('------------')
print(a1[2,2])           #selected 2nd row and column
print(a1[1 : , 1 : 2])   #selected only 1st column and 1st, 2nd, 3rd rows
print('------------')
print(a1[2,1])
print(a1[1 : , 1 : 2])   #selected only 1st column and 1st, 2nd, 3rd rows
print('------------')
#Cropping the elements
print(a1[2 : , 1 : ])

1
------------
[1 2]
------------
[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]
------------
[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]
------------
[[5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]
------------
[8 7 6 5]
------------
[[6 7 8]
 [7 6 5]
 [3 2 1]]
------------
[[6]
 [7]
 [3]]
------------
6
[[6]
 [7]
 [3]]
------------
7
[[6]
 [7]
 [3]]
------------
[[7 6 5]
 [3 2 1]]


Video 7 Automating using NumPy

In [37]:
import numpy as np
lst = [1,2,3,4,5,6,7,8,9,10]
count = 0
for i in lst:
    if(i>4):
        count += 1
    
print(count)

print('------------------------------------')
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr > 5)
arr[arr > 5]

6
------------------------------------
[False False False False False  True  True  True  True  True]


array([ 6,  7,  8,  9, 10])

In [38]:
list = [1,2,3,'I', 'am','chetan']
print(list)

[1, 2, 3, 'I', 'am', 'chetan']
